# The address to listen on for incoming requests.
listen_address = "127.0.0.1:5000"

# Must be set to true in order to listen on non-loopback addresses.
#
# Think carefully before you enable this setting. The symbol servers are
# authenticated for a reason, and this application is not designed to
# authenticate incoming requests nor will it ever do so.
# Ensure that you have either properly firewalled this application, or
# set up a layer in front of the application (such as nginx) that can
# authenticate incoming requests.
i_am_not_an_idiot = false

# Optional settings to configure symbol caching via an Azure storage account.
# MI authentication is the only mode supported, so you must grant the
# application's identity access to your storage account.
#[cache]
# The name of the storage account to use as a cache.
#storage_account = ""
# The container within the storage account to use.
#storage_container = ""

[[servers]]
# The upstream symbol server.
url = "https://msdl.microsoft.com/download/symbols"

# The scope of the token. Typically looks like `api://XXXX.../.default`
# Omit this parameter to use a server that supports unauthenticated access.
#scope = ""

# You can include any number of additional symbol servers.
# The proxy tool will try them in order when serving symbol requests.
#[[servers]]
#url = "..."
