# The address to listen on for incoming requests.
listen_address = "127.0.0.1:5000"

# Must be set to true in order to listen on non-loopback addresses.
#
# Think carefully before you enable this setting. The symbol servers are
# authenticated for a reason, and this application is not designed to
# authenticate incoming requests nor will it ever do so.
# Ensure that you have either properly firewalled this application, or
# set up a layer in front of the application (such as nginx) that can
# authenticate incoming requests.
i_am_not_an_idiot = false

# Optional settings to configure symbol caching in Azure DevOps.
# MI authentication is exclusively used for ADO, so you must authorize
# this application's identity in your organization.
# https://learn.microsoft.com/en-us/azure/devops/integrate/get-started/authentication/service-principal-managed-identity?view=azure-devops#2-add-and-manage-service-principals-in-an-azure-devops-organization
[cache]
# The path to the Azure DevOps symbol app.
# Relative to the CWD of the application at runtime.
symbol_path = "./symbol.app/lib/net45/symbol.exe"

# The Azure DevOps organization used to cache symbols. Can either be
# the name or the GUID of the organization.
organization = "example"

[[servers]]
# The upstream symbol server.
url = "https://msdl.microsoft.com/download/symbols"

# The scope of the token. Typically looks like `api://XXXX.../.default`
# Omit this parameter to use a server that supports unauthenticated access.
# scope = ""

# You can include any number of additional symbol servers.
# The proxy tool will try them in order when serving symbol requests.
# [[servers]]
# url = "..."
