# GENERATED BY: ChatGPT-5.5
import contextlib
import functools
import http.server
import json
import os
import shlex
import shutil
import socket
import subprocess
import tempfile
import threading
import time
import unittest
import urllib.error
import urllib.request
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]


def get_free_port():
    with contextlib.closing(socket.socket(socket.AF_INET, socket.SOCK_STREAM)) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


class QuietDirectoryHandler(http.server.SimpleHTTPRequestHandler):
    def log_message(self, format, *args):
        pass


class UpstreamServer:
    def __init__(self, directory):
        self.directory = Path(directory)
        self.port = get_free_port()
        handler = functools.partial(QuietDirectoryHandler, directory=str(self.directory))
        self.server = http.server.ThreadingHTTPServer(("127.0.0.1", self.port), handler)
        self.thread = threading.Thread(target=self.server.serve_forever, daemon=True)

    @property
    def url(self):
        return f"http://127.0.0.1:{self.port}/"

    def __enter__(self):
        self.thread.start()
        return self

    def __exit__(self, exc_type, exc, tb):
        self.server.shutdown()
        self.server.server_close()
        self.thread.join(timeout=5)


class SymProxyCloud:
    def __init__(self, listen_port, env):
        self.listen_port = listen_port
        self.env = env
        self.process = None

    @property
    def base_url(self):
        return f"http://127.0.0.1:{self.listen_port}"

    def __enter__(self):
        extra_args = shlex.split(os.environ.get("SYMPROXYCLOUD_EXTRA_ARGS", ""))
        binary = os.environ.get("SYMPROXYCLOUD_BIN")
        if binary:
            command = [binary, *extra_args]
        else:
            command = [
                "cargo",
                "run",
                "--quiet",
                "--release",
                "--",
                *extra_args,
            ]

        show_logs = os.environ.get("SYMPROXYCLOUD_SHOW_LOGS") == "1"
        self.process = subprocess.Popen(
            command,
            cwd=REPO_ROOT,
            env=self.env,
            stdout=None if show_logs else subprocess.PIPE,
            stderr=None if show_logs else subprocess.STDOUT,
            text=True,
        )
        try:
            self._wait_until_ready()
        except Exception:
            self.stop()
            raise
        return self

    def __exit__(self, exc_type, exc, tb):
        self.stop()

    def stop(self):
        if self.process is None:
            return

        if self.process.poll() is None:
            self.process.terminate()
            try:
                self.process.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self.process.kill()
                self.process.wait(timeout=5)
        if self.process.stdout:
            self.process.stdout.close()
        self.process = None

    def _wait_until_ready(self):
        deadline = time.monotonic() + 120
        last_error = None

        while time.monotonic() < deadline:
            if self.process.poll() is not None:
                output = self.process.stdout.read() if self.process.stdout else ""
                raise AssertionError(
                    f"SymProxyCloud exited before becoming ready with code "
                    f"{self.process.returncode}.\n{output}"
                )

            try:
                request("GET", f"{self.base_url}/health")
                return
            except (urllib.error.URLError, urllib.error.HTTPError) as error:
                last_error = error
                time.sleep(0.1)

        raise AssertionError(f"SymProxyCloud did not become ready: {last_error}")


def request(method, url):
    req = urllib.request.Request(url, method=method)
    try:
        with urllib.request.urlopen(req, timeout=5) as response:
            return response.status, response.headers, response.read()
    except urllib.error.HTTPError as error:
        return error.code, error.headers, error.read()


def figment_string(value):
    return json.dumps(str(value))


def symproxy_env(listen_port, upstream_url, cache_dir=None):
    env = {
        key: value
        for key, value in os.environ.items()
        if not key.upper().startswith("SYMPROXY_")
    }
    env.update(
        {
            "SYMPROXY_LISTEN_ADDRESS": f"127.0.0.1:{listen_port}",
            "SYMPROXY_I_AM_NOT_AN_IDIOT": "false",
            "SYMPROXY_MAX_RETRIES": "0",
            "SYMPROXY_SERVERS": f"[{{url={figment_string(upstream_url)}}}]",
        }
    )
    if cache_dir is not None:
        env["SYMPROXY_CACHE"] = (
            f'{{type="fs",path={figment_string(Path(cache_dir))}}}'
        )
    return env


def write_symbol(root, name, hash_value, file_name, content):
    path = Path(root) / name / hash_value / file_name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    return path


class SymProxyCloudIntegrationTests(unittest.TestCase):
    def test_proxies_existing_symbol_from_upstream(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            symbol_content = b"example pdb bytes\n"
            write_symbol(temp_path / "upstream", "example.pdb", "ABC123", "example.pdb", symbol_content)

            with UpstreamServer(temp_path / "upstream") as upstream:
                listen_port = get_free_port()

                with SymProxyCloud(
                    listen_port, symproxy_env(listen_port, upstream.url)
                ) as proxy:
                    status, headers, body = request(
                        "GET", f"{proxy.base_url}/example.pdb/ABC123/example.pdb"
                    )

            self.assertEqual(status, 200)
            self.assertEqual(body, symbol_content)
            self.assertEqual(headers["X-Upstream-Source"], "server")
            self.assertEqual(headers["X-Upstream-Server"], upstream.url)

    def test_returns_404_for_missing_symbol(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            write_symbol(temp_path / "upstream", "present.pdb", "ABC123", "present.pdb", b"present")

            with UpstreamServer(temp_path / "upstream") as upstream:
                listen_port = get_free_port()

                with SymProxyCloud(
                    listen_port, symproxy_env(listen_port, upstream.url)
                ) as proxy:
                    status, headers, body = request(
                        "GET", f"{proxy.base_url}/missing.pdb/DEADBEEF/missing.pdb"
                    )

            self.assertEqual(status, 404)
            self.assertEqual(body, b"")
            self.assertNotIn("X-Upstream-Source", headers)

    def test_filesystem_cache_mirrors_and_serves_symbol(self):
        with tempfile.TemporaryDirectory() as temp_dir:
            temp_path = Path(temp_dir)
            upstream_root = temp_path / "upstream"
            cache_root = temp_path / "cache"
            symbol_content = b"cacheable pdb bytes\n"
            symbol_path = ("cacheable.pdb", "C0FFEE", "cacheable.pdb")
            write_symbol(upstream_root, *symbol_path, symbol_content)

            with UpstreamServer(upstream_root) as upstream:
                listen_port = get_free_port()

                with SymProxyCloud(
                    listen_port, symproxy_env(listen_port, upstream.url, cache_root)
                ) as proxy:
                    url = f"{proxy.base_url}/{'/'.join(symbol_path)}"
                    status, headers, body = request("GET", url)

                    self.assertEqual(status, 200)
                    self.assertEqual(body, symbol_content)
                    self.assertEqual(headers["X-Upstream-Source"], "server")

                    cached_file = cache_root.joinpath(*symbol_path)
                    wait_for_file(cached_file)

                    shutil.rmtree(upstream_root)
                    status, headers, body = request("GET", url)

            self.assertEqual(status, 200)
            self.assertEqual(body, symbol_content)
            self.assertEqual(headers["X-Upstream-Source"], "cache")


def wait_for_file(path):
    deadline = time.monotonic() + 5
    while time.monotonic() < deadline:
        if Path(path).is_file():
            return
        time.sleep(0.05)
    raise AssertionError(f"Timed out waiting for cache file: {path}")


if __name__ == "__main__":
    unittest.main()
